name = "EnderIO Test Server"
author = "Team-EnderIO"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79d01dfcd360a8729f1f1c8f162ab8de62b7aa33c07ba6a8fc7c9cfa9687ab56"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
