name = "EnderIO Test Server"
author = "Team-EnderIO"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99a0c2c15fa2040f52360d5a63ca74f5f4ffbc70e48c43a6e27dcdac77450f07"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
